Repository Lenigir-Srl/risto89, pull requests merged in 2024-04, with the labels that each got.

#22 Fixes #9: Removed target/ directory from repository
  target/classes/HelloServlet.class
  target/maven-archiver/pom.properties
  target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
  target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
  target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/createdFiles.lst
  target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/inputFiles.lst
  target/servlet-1.0.war
  target/servlet-1.0/WEB-INF/classes/HelloServlet.class
  target/servlet-1.0/WEB-INF/web.xml
  target/servlet-1.0/index.html
  target/servlet-1.0/index.jsp
Labels: enhancement, help wanted

#28 Fixes #3: Created a login page
  src/main/java/Login.java
  src/main/webapp/Homepage.html
  src/main/webapp/Loginpage.html
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/bootstrap_prova.html
  src/main/webapp/index.html
Labels: good first issue, request

#53 Added DB connection per Session
  src/main/java/Error.java
  src/main/java/Login.java
  src/main/java/SessionConnection.java
  src/main/webapp/WEB-INF/web.xml
Labels: enhancement

#58 Added "testo consegna"
  README.md
  Testo_Progetto.pdf
Labels: enhancement
